apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-longhorn-claim
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
    limits:
      storage: 10Gi
  storageClassName: longhorn
