apiVersion: v1
kind: Pod
metadata:
  name: 02-pod-demoapp-env
  labels:
    app: demoapp
    release: cannary
spec:
  containers:
  - name: demoapp
    image: ikubernetes/demoapp:v1.0
    env:
    - name: HOST
      value: "127.0.0.1"
