apiVersion: v1
kind: Pod
metadata:
  name: 03-pod-demoapp-ports
  labels:
    app: demoapp
    release: cannary
spec:
  containers:
  - name: demoapp
    image: ikubernetes/demoapp:v1.0
    ports:
    - name: http
      protocol: TCP
      containerPort: 80
      #hostPort: 10080
