apiVersion: v1
kind: Pod
metadata:
  name: 05-pod-demoapp-securitycontext-runasuser
  labels:
    app: demoapp
    release: cannary
spec:
  containers:
  - name: demoapp
    image: ikubernetes/demoapp:v1.0
    imagePullPolicy: IfNotPresent
    env:
    - name: PORT
      value: "8080"
    securityContext:
      runAsUser: 1001
      runAsGroup: 1001
