apiVersion: v1
kind: Pod
metadata:
  name: 07-pod-demoapp-securitycontext-sysctls
  labels:
    app: demoapp
    release: cannary
spec:
  securityContext:
    sysctls:
    - name: kernel.shm_rmid_forced
      value: "0"
    - name: net.ipv4.ip_unprivileges_port_start
      value: "0"
  containers:
  - name: demoapp
    image: ikubernetes/demoapp:v1.0
    imagePullPolicy: IfNotPresent
    securityContext:
      capabilities:
        add: ['NET_ADMIN']
        drop: ['CHOWN']

# echo "KUBELET_EXTRA_ARGS='--allowed-unsafe-sysctls=net.core.somaxconn,net.ipv4.ip_unprivileged_port_start'" > /etc/default/kubelet
# systemctl restart kubelet
