apiVersion: v1
kind: Pod
metadata:
  name: 08-pod-demoapp-liveness-exec.yaml
  labels:
    app: demoapp
    release: cannary
spec:
  containers:
  - name: demoapp
    image: ikubernetes/demoapp:v1.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command: ['/bin/sh', '-c', '[ "$(curl -s 127.0.0.1/livez)" == "OK"']
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 5
#  curl -XPOST -d 'livez=FAIL' http://10.244.2.14/livez
