apiVersion: v1
kind: Pod
metadata:
  name: 09-pod-demoapp-liveness-tcpsocket
  labels:
    app: demoapp
    release: cannary
spec:
  containers:
  - name: demoapp
    image: ikubernetes/demoapp:v1.0
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 80
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
    livenessProbe:
      tcpSocket:
        port: http
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 5
# kubectl  exec 09-pod-demoapp-liveness-tcpsocket -- iptables -A INPUT -p tcp --dport 80 -j REJECT
