---
apiVersion: v1
kind: Service
metadata:
  name: pod-demoapp-svc-headless
  namespace: default
spec:
  clusterIP: None
  selector:
    app: demoapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-demoapp
  labels:
    app: demoapp
    release: cannary
spec:
  containers:
  - name: demoapp
    image: ikubernetes/demoapp:v1.0

# kubectl  exec -it pod-demoapp --  nslookup pod-demoapp-svc-headless.default.svc.cluster.local
