---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-auth
stringData:
  username: root
  password: mypass
type: Opaque

# kubectl  create secret generic mysql-root-auth --from-literal=username=root --from-literal=password=mypass

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-generic-demo
  namespace: default
spec:
  containers:
  - name: mariadb
    image: mariadb
    imagePullPolicy: IfNotPresent
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-root-auth
          key: password

